"""schema_v1

Revision ID: 0002
Revises: 0001
Create Date: 2026-07-03 01:06:18.449417
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_name", sa.String(length=120), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("detail", sa.JSON(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_runs")),
    )
    op.create_index(
        op.f("ix_job_runs_job_name"), "job_runs", ["job_name"], unique=False
    )
    op.create_index(op.f("ix_job_runs_status"), "job_runs", ["status"], unique=False)
    op.create_table(
        "model_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("artifact_path", sa.String(length=512), nullable=False),
        sa.Column("feature_version", sa.String(length=64), nullable=False),
        sa.Column("training_metadata", sa.JSON(), nullable=True),
        sa.Column("metrics", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_versions")),
        sa.UniqueConstraint("name", "version", name="uq_model_versions_name_version"),
    )
    op.create_index(
        op.f("ix_model_versions_feature_version"),
        "model_versions",
        ["feature_version"],
        unique=False,
    )
    op.create_table(
        "prompt_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("template", sa.Text(), nullable=False),
        sa.Column("schema", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prompt_versions")),
        sa.UniqueConstraint("name", "version", name="uq_prompt_versions_name_version"),
    )
    op.create_table(
        "raw_source_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("endpoint", sa.String(length=255), nullable=False),
        sa.Column("params", sa.JSON(), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("raw_json", sa.JSON(), nullable=False),
        sa.Column("raw_hash", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_raw_source_snapshots")),
    )
    op.create_index(
        op.f("ix_raw_source_snapshots_endpoint"),
        "raw_source_snapshots",
        ["endpoint"],
        unique=False,
    )
    op.create_index(
        op.f("ix_raw_source_snapshots_raw_hash"),
        "raw_source_snapshots",
        ["raw_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_raw_source_snapshots_source"),
        "raw_source_snapshots",
        ["source"],
        unique=False,
    )
    op.create_index(
        op.f("ix_raw_source_snapshots_status"),
        "raw_source_snapshots",
        ["status"],
        unique=False,
    )
    op.create_table(
        "source_health_checks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_name", sa.String(length=64), nullable=False),
        sa.Column("checked_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("sample_entity", sa.String(length=120), nullable=True),
        sa.Column("response_shape_hash", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_health_checks")),
    )
    op.create_index(
        op.f("ix_source_health_checks_checked_at"),
        "source_health_checks",
        ["checked_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_source_health_checks_response_shape_hash"),
        "source_health_checks",
        ["response_shape_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_source_health_checks_source_name"),
        "source_health_checks",
        ["source_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_source_health_checks_status"),
        "source_health_checks",
        ["status"],
        unique=False,
    )
    op.create_table(
        "teams",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("external_team_id", sa.String(length=64), nullable=True),
        sa.Column("abbreviation", sa.String(length=12), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("city", sa.String(length=120), nullable=True),
        sa.Column("conference", sa.String(length=32), nullable=True),
        sa.Column("division", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_teams")),
        sa.UniqueConstraint("abbreviation", name=op.f("uq_teams_abbreviation")),
        sa.UniqueConstraint("external_team_id", name=op.f("uq_teams_external_team_id")),
    )
    op.create_table(
        "games",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("external_game_id", sa.String(length=64), nullable=False),
        sa.Column("home_team_id", sa.Integer(), nullable=False),
        sa.Column("away_team_id", sa.Integer(), nullable=False),
        sa.Column("game_date", sa.Date(), nullable=False),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("season", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["away_team_id"], ["teams.id"], name=op.f("fk_games_away_team_id_teams")
        ),
        sa.ForeignKeyConstraint(
            ["home_team_id"], ["teams.id"], name=op.f("fk_games_home_team_id_teams")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_games")),
        sa.UniqueConstraint("external_game_id", name=op.f("uq_games_external_game_id")),
    )
    op.create_index(
        op.f("ix_games_away_team_id"), "games", ["away_team_id"], unique=False
    )
    op.create_index(
        "ix_games_away_team_id_game_date",
        "games",
        ["away_team_id", "game_date"],
        unique=False,
    )
    op.create_index(op.f("ix_games_game_date"), "games", ["game_date"], unique=False)
    op.create_index(
        op.f("ix_games_home_team_id"), "games", ["home_team_id"], unique=False
    )
    op.create_index(
        "ix_games_home_team_id_game_date",
        "games",
        ["home_team_id", "game_date"],
        unique=False,
    )
    op.create_index(op.f("ix_games_season"), "games", ["season"], unique=False)
    op.create_index(op.f("ix_games_status"), "games", ["status"], unique=False)
    op.create_table(
        "llm_call_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=120), nullable=False),
        sa.Column("prompt_version_id", sa.Integer(), nullable=True),
        sa.Column("request_metadata", sa.JSON(), nullable=True),
        sa.Column("response_metadata", sa.JSON(), nullable=True),
        sa.Column("tokens_in", sa.Integer(), nullable=True),
        sa.Column("tokens_out", sa.Integer(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("validation_ok", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["prompt_version_id"],
            ["prompt_versions.id"],
            name=op.f("fk_llm_call_logs_prompt_version_id_prompt_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_llm_call_logs")),
    )
    op.create_index(
        op.f("ix_llm_call_logs_model"), "llm_call_logs", ["model"], unique=False
    )
    op.create_index(
        op.f("ix_llm_call_logs_prompt_version_id"),
        "llm_call_logs",
        ["prompt_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_llm_call_logs_provider"), "llm_call_logs", ["provider"], unique=False
    )
    op.create_table(
        "players",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("external_player_id", sa.String(length=64), nullable=True),
        sa.Column("team_id", sa.Integer(), nullable=True),
        sa.Column("first_name", sa.String(length=80), nullable=True),
        sa.Column("last_name", sa.String(length=80), nullable=True),
        sa.Column("full_name", sa.String(length=160), nullable=False),
        sa.Column("position", sa.String(length=32), nullable=True),
        sa.Column("active", sa.Boolean(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["team_id"], ["teams.id"], name=op.f("fk_players_team_id_teams")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_players")),
        sa.UniqueConstraint(
            "external_player_id", name=op.f("uq_players_external_player_id")
        ),
    )
    op.create_index(
        op.f("ix_players_full_name"), "players", ["full_name"], unique=False
    )
    op.create_index(op.f("ix_players_team_id"), "players", ["team_id"], unique=False)
    op.create_table(
        "feature_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("stat_type", sa.String(length=32), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("feature_version", sa.String(length=64), nullable=False),
        sa.Column("features", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["game_id"], ["games.id"], name=op.f("fk_feature_snapshots_game_id_games")
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
            name=op.f("fk_feature_snapshots_player_id_players"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feature_snapshots")),
        sa.UniqueConstraint(
            "player_id",
            "game_id",
            "stat_type",
            "as_of",
            "feature_version",
            name="uq_feature_snapshots_player_game_stat_as_of_version",
        ),
    )
    op.create_index(
        op.f("ix_feature_snapshots_as_of"), "feature_snapshots", ["as_of"], unique=False
    )
    op.create_index(
        op.f("ix_feature_snapshots_feature_version"),
        "feature_snapshots",
        ["feature_version"],
        unique=False,
    )
    op.create_index(
        op.f("ix_feature_snapshots_game_id"),
        "feature_snapshots",
        ["game_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_feature_snapshots_player_id"),
        "feature_snapshots",
        ["player_id"],
        unique=False,
    )
    op.create_index(
        "ix_feature_snapshots_player_id_game_id",
        "feature_snapshots",
        ["player_id", "game_id"],
        unique=False,
    )
    op.create_table(
        "injury_reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["game_id"], ["games.id"], name=op.f("fk_injury_reports_game_id_games")
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
            name=op.f("fk_injury_reports_player_id_players"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_injury_reports")),
    )
    op.create_index(
        op.f("ix_injury_reports_game_id"), "injury_reports", ["game_id"], unique=False
    )
    op.create_index(
        op.f("ix_injury_reports_player_id"),
        "injury_reports",
        ["player_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_injury_reports_source"), "injury_reports", ["source"], unique=False
    )
    op.create_index(
        op.f("ix_injury_reports_status"), "injury_reports", ["status"], unique=False
    )
    op.create_table(
        "player_game_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("matchup", sa.String(length=32), nullable=True),
        sa.Column("is_home", sa.Boolean(), nullable=False),
        sa.Column("pts", sa.Float(), nullable=True),
        sa.Column("minutes", sa.Float(), nullable=True),
        sa.Column("fga", sa.Float(), nullable=True),
        sa.Column("fg_pct", sa.Float(), nullable=True),
        sa.Column("reb", sa.Float(), nullable=True),
        sa.Column("ast", sa.Float(), nullable=True),
        sa.Column("fg3_pct", sa.Float(), nullable=True),
        sa.Column("ft_pct", sa.Float(), nullable=True),
        sa.Column("plus_minus", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["game_id"], ["games.id"], name=op.f("fk_player_game_logs_game_id_games")
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
            name=op.f("fk_player_game_logs_player_id_players"),
        ),
        sa.ForeignKeyConstraint(
            ["team_id"], ["teams.id"], name=op.f("fk_player_game_logs_team_id_teams")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_player_game_logs")),
        sa.UniqueConstraint(
            "player_id", "game_id", name="uq_player_game_logs_player_game"
        ),
    )
    op.create_index(
        op.f("ix_player_game_logs_game_id"),
        "player_game_logs",
        ["game_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_player_game_logs_player_id"),
        "player_game_logs",
        ["player_id"],
        unique=False,
    )
    op.create_index(
        "ix_player_game_logs_player_id_game_id",
        "player_game_logs",
        ["player_id", "game_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_player_game_logs_team_id"),
        "player_game_logs",
        ["team_id"],
        unique=False,
    )
    op.create_table(
        "prop_lines",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=True),
        sa.Column("stat_type", sa.String(length=32), nullable=False),
        sa.Column("line_value", sa.Float(), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("stale", sa.Boolean(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["game_id"], ["games.id"], name=op.f("fk_prop_lines_game_id_games")
        ),
        sa.ForeignKeyConstraint(
            ["player_id"], ["players.id"], name=op.f("fk_prop_lines_player_id_players")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prop_lines")),
    )
    op.create_index(
        op.f("ix_prop_lines_game_id"), "prop_lines", ["game_id"], unique=False
    )
    op.create_index(
        op.f("ix_prop_lines_player_id"), "prop_lines", ["player_id"], unique=False
    )
    op.create_index(
        "ix_prop_lines_player_id_stat_type_fetched_at",
        "prop_lines",
        ["player_id", "stat_type", "fetched_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_prop_lines_source"), "prop_lines", ["source"], unique=False
    )
    op.create_table(
        "team_game_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("matchup", sa.String(length=32), nullable=True),
        sa.Column("is_home", sa.Boolean(), nullable=False),
        sa.Column("pts", sa.Float(), nullable=True),
        sa.Column("minutes", sa.Float(), nullable=True),
        sa.Column("fga", sa.Float(), nullable=True),
        sa.Column("fg_pct", sa.Float(), nullable=True),
        sa.Column("reb", sa.Float(), nullable=True),
        sa.Column("ast", sa.Float(), nullable=True),
        sa.Column("fg3_pct", sa.Float(), nullable=True),
        sa.Column("ft_pct", sa.Float(), nullable=True),
        sa.Column("plus_minus", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["game_id"], ["games.id"], name=op.f("fk_team_game_logs_game_id_games")
        ),
        sa.ForeignKeyConstraint(
            ["team_id"], ["teams.id"], name=op.f("fk_team_game_logs_team_id_teams")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_team_game_logs")),
        sa.UniqueConstraint("team_id", "game_id", name="uq_team_game_logs_team_game"),
    )
    op.create_index(
        op.f("ix_team_game_logs_game_id"), "team_game_logs", ["game_id"], unique=False
    )
    op.create_index(
        op.f("ix_team_game_logs_team_id"), "team_game_logs", ["team_id"], unique=False
    )
    op.create_index(
        "ix_team_game_logs_team_id_game_id",
        "team_game_logs",
        ["team_id", "game_id"],
        unique=False,
    )
    op.create_table(
        "prediction_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("model_version_id", sa.Integer(), nullable=False),
        sa.Column("prompt_version_id", sa.Integer(), nullable=False),
        sa.Column("feature_snapshot_id", sa.Integer(), nullable=True),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("llm_model", sa.String(length=120), nullable=False),
        sa.Column("context_hash", sa.String(length=128), nullable=False),
        sa.Column("data_quality", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["feature_snapshot_id"],
            ["feature_snapshots.id"],
            name=op.f("fk_prediction_runs_feature_snapshot_id_feature_snapshots"),
        ),
        sa.ForeignKeyConstraint(
            ["model_version_id"],
            ["model_versions.id"],
            name=op.f("fk_prediction_runs_model_version_id_model_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["prompt_version_id"],
            ["prompt_versions.id"],
            name=op.f("fk_prediction_runs_prompt_version_id_prompt_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prediction_runs")),
    )
    op.create_index(
        op.f("ix_prediction_runs_context_hash"),
        "prediction_runs",
        ["context_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_prediction_runs_feature_snapshot_id"),
        "prediction_runs",
        ["feature_snapshot_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_prediction_runs_model_version_id"),
        "prediction_runs",
        ["model_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_prediction_runs_prompt_version_id"),
        "prediction_runs",
        ["prompt_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_prediction_runs_provider"),
        "prediction_runs",
        ["provider"],
        unique=False,
    )
    op.create_index(
        op.f("ix_prediction_runs_status"), "prediction_runs", ["status"], unique=False
    )
    op.create_table(
        "player_predictions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("prediction_run_id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("stat_type", sa.String(length=32), nullable=False),
        sa.Column("line", sa.Float(), nullable=False),
        sa.Column("base_prediction", sa.Float(), nullable=True),
        sa.Column("final_prediction", sa.Float(), nullable=False),
        sa.Column("predicted_range_low", sa.Float(), nullable=True),
        sa.Column("predicted_range_high", sa.Float(), nullable=True),
        sa.Column("over_under_recommendation", sa.String(length=16), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("raw_llm_output", sa.JSON(), nullable=True),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column("is_current", sa.Boolean(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["game_id"], ["games.id"], name=op.f("fk_player_predictions_game_id_games")
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
            name=op.f("fk_player_predictions_player_id_players"),
        ),
        sa.ForeignKeyConstraint(
            ["prediction_run_id"],
            ["prediction_runs.id"],
            name=op.f("fk_player_predictions_prediction_run_id_prediction_runs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_player_predictions")),
    )
    op.create_index(
        op.f("ix_player_predictions_game_id"),
        "player_predictions",
        ["game_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_player_predictions_player_id"),
        "player_predictions",
        ["player_id"],
        unique=False,
    )
    op.create_index(
        "ix_player_predictions_player_id_game_id_stat_type",
        "player_predictions",
        ["player_id", "game_id", "stat_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_player_predictions_prediction_run_id"),
        "player_predictions",
        ["prediction_run_id"],
        unique=False,
    )
    op.create_table(
        "prediction_evaluations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("player_prediction_id", sa.Integer(), nullable=False),
        sa.Column("actual_value", sa.Float(), nullable=False),
        sa.Column("error", sa.Float(), nullable=True),
        sa.Column("line_hit", sa.Boolean(), nullable=True),
        sa.Column("over_under_correct", sa.Boolean(), nullable=True),
        sa.Column("evaluated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["player_prediction_id"],
            ["player_predictions.id"],
            name=op.f(
                "fk_prediction_evaluations_player_prediction_id_player_predictions"
            ),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prediction_evaluations")),
    )
    op.create_index(
        op.f("ix_prediction_evaluations_player_prediction_id"),
        "prediction_evaluations",
        ["player_prediction_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_prediction_evaluations_player_prediction_id"),
        table_name="prediction_evaluations",
    )
    op.drop_table("prediction_evaluations")
    op.drop_index(
        op.f("ix_player_predictions_prediction_run_id"), table_name="player_predictions"
    )
    op.drop_index(
        "ix_player_predictions_player_id_game_id_stat_type",
        table_name="player_predictions",
    )
    op.drop_index(
        op.f("ix_player_predictions_player_id"), table_name="player_predictions"
    )
    op.drop_index(
        op.f("ix_player_predictions_game_id"), table_name="player_predictions"
    )
    op.drop_table("player_predictions")
    op.drop_index(op.f("ix_prediction_runs_status"), table_name="prediction_runs")
    op.drop_index(op.f("ix_prediction_runs_provider"), table_name="prediction_runs")
    op.drop_index(
        op.f("ix_prediction_runs_prompt_version_id"), table_name="prediction_runs"
    )
    op.drop_index(
        op.f("ix_prediction_runs_model_version_id"), table_name="prediction_runs"
    )
    op.drop_index(
        op.f("ix_prediction_runs_feature_snapshot_id"), table_name="prediction_runs"
    )
    op.drop_index(op.f("ix_prediction_runs_context_hash"), table_name="prediction_runs")
    op.drop_table("prediction_runs")
    op.drop_index("ix_team_game_logs_team_id_game_id", table_name="team_game_logs")
    op.drop_index(op.f("ix_team_game_logs_team_id"), table_name="team_game_logs")
    op.drop_index(op.f("ix_team_game_logs_game_id"), table_name="team_game_logs")
    op.drop_table("team_game_logs")
    op.drop_index(op.f("ix_prop_lines_source"), table_name="prop_lines")
    op.drop_index(
        "ix_prop_lines_player_id_stat_type_fetched_at", table_name="prop_lines"
    )
    op.drop_index(op.f("ix_prop_lines_player_id"), table_name="prop_lines")
    op.drop_index(op.f("ix_prop_lines_game_id"), table_name="prop_lines")
    op.drop_table("prop_lines")
    op.drop_index(op.f("ix_player_game_logs_team_id"), table_name="player_game_logs")
    op.drop_index(
        "ix_player_game_logs_player_id_game_id", table_name="player_game_logs"
    )
    op.drop_index(op.f("ix_player_game_logs_player_id"), table_name="player_game_logs")
    op.drop_index(op.f("ix_player_game_logs_game_id"), table_name="player_game_logs")
    op.drop_table("player_game_logs")
    op.drop_index(op.f("ix_injury_reports_status"), table_name="injury_reports")
    op.drop_index(op.f("ix_injury_reports_source"), table_name="injury_reports")
    op.drop_index(op.f("ix_injury_reports_player_id"), table_name="injury_reports")
    op.drop_index(op.f("ix_injury_reports_game_id"), table_name="injury_reports")
    op.drop_table("injury_reports")
    op.drop_index(
        "ix_feature_snapshots_player_id_game_id", table_name="feature_snapshots"
    )
    op.drop_index(
        op.f("ix_feature_snapshots_player_id"), table_name="feature_snapshots"
    )
    op.drop_index(op.f("ix_feature_snapshots_game_id"), table_name="feature_snapshots")
    op.drop_index(
        op.f("ix_feature_snapshots_feature_version"), table_name="feature_snapshots"
    )
    op.drop_index(op.f("ix_feature_snapshots_as_of"), table_name="feature_snapshots")
    op.drop_table("feature_snapshots")
    op.drop_index(op.f("ix_players_team_id"), table_name="players")
    op.drop_index(op.f("ix_players_full_name"), table_name="players")
    op.drop_table("players")
    op.drop_index(op.f("ix_llm_call_logs_provider"), table_name="llm_call_logs")
    op.drop_index(
        op.f("ix_llm_call_logs_prompt_version_id"), table_name="llm_call_logs"
    )
    op.drop_index(op.f("ix_llm_call_logs_model"), table_name="llm_call_logs")
    op.drop_table("llm_call_logs")
    op.drop_index(op.f("ix_games_status"), table_name="games")
    op.drop_index(op.f("ix_games_season"), table_name="games")
    op.drop_index("ix_games_home_team_id_game_date", table_name="games")
    op.drop_index(op.f("ix_games_home_team_id"), table_name="games")
    op.drop_index(op.f("ix_games_game_date"), table_name="games")
    op.drop_index("ix_games_away_team_id_game_date", table_name="games")
    op.drop_index(op.f("ix_games_away_team_id"), table_name="games")
    op.drop_table("games")
    op.drop_table("teams")
    op.drop_index(
        op.f("ix_source_health_checks_status"), table_name="source_health_checks"
    )
    op.drop_index(
        op.f("ix_source_health_checks_source_name"), table_name="source_health_checks"
    )
    op.drop_index(
        op.f("ix_source_health_checks_response_shape_hash"),
        table_name="source_health_checks",
    )
    op.drop_index(
        op.f("ix_source_health_checks_checked_at"), table_name="source_health_checks"
    )
    op.drop_table("source_health_checks")
    op.drop_index(
        op.f("ix_raw_source_snapshots_status"), table_name="raw_source_snapshots"
    )
    op.drop_index(
        op.f("ix_raw_source_snapshots_source"), table_name="raw_source_snapshots"
    )
    op.drop_index(
        op.f("ix_raw_source_snapshots_raw_hash"), table_name="raw_source_snapshots"
    )
    op.drop_index(
        op.f("ix_raw_source_snapshots_endpoint"), table_name="raw_source_snapshots"
    )
    op.drop_table("raw_source_snapshots")
    op.drop_table("prompt_versions")
    op.drop_index(
        op.f("ix_model_versions_feature_version"), table_name="model_versions"
    )
    op.drop_table("model_versions")
    op.drop_index(op.f("ix_job_runs_status"), table_name="job_runs")
    op.drop_index(op.f("ix_job_runs_job_name"), table_name="job_runs")
    op.drop_table("job_runs")
    # ### end Alembic commands ###
